import ListCar from "@/components/list-car/list-car";
export { default as Navbar } from "./navbar/navbar";
export { default as ImageUI } from "./ImageUI/Image-UI";
export { default as IndexBanner } from "./index-banner/index-banner";
export { default as IndexCard } from "./index-card/index-card";
export { default as Footer } from "./footer/footer";
export { default as SectionTitle } from "./section-title/section-title";
export { default as Video } from "./video/video";
export { default as SwiperSection } from "./swiper-section/swiper-section";
export { default as  ConfigurationsSection} from "./configuration-section/configurations-section";
export { default as  PositionCard} from "./position-card/position-card";
export { default as  ListCar} from "./list-car/list-car";
export { default as  CardL9} from "./card-l9/card-l9";
export { default as  HeaderBannerAbout} from "./header-banner-about/header-banner-about";
